### PR TITLE
Fix Everything!

### PR DESCRIPTION
**Pull request by DrFacepalm**
This MR adds vue into this demo.

### CODE REVIEW

**Comment by CMCDragonkai** [comment]
Right now:

```
# runs webpack to build dist
npm run build
# builds the nix package electron application
nix-build ./release.nix --attr application
```

So nix builds actually works... we get  a working electron application.

**Comment by CMCDragonkai** [comment]
@gideonairex @scottmmorris watch this.

**Comment by CMCDragonkai** [comment]
What we are attempting now is to integrate the `electron-forge` build to build target platforms here too.

**Comment by CMCDragonkai** [comment]
Note that running `electron` on the current project directory would run against the `package.json` which points to the `dist`. So you can develop by doing:

```
npm run build
electron .
```

I'm not sure if there's a hot reloading thing similar to `npm run server` which will reload the electron runtime with the build webpack. There probably is. But I'm sure @gideonairex knows about it.

**Comment by CMCDragonkai** [comment]
The convention is to use `index.js`, not `main.js`. This needs to be changed.

**Comment by CMCDragonkai** [comment]
The dist is now:

```
»» ~/Projects/Typescript-Demo-Electron
 ♖ tree dist                                                (vue) pts/9 22:54:48
dist
├── index.css
├── index.html
├── index.js
└── renderer.js

0 directories, 4 files
```

The `index.js` means that you can do `electron dist`.

Even the `package.json` is not really necessary anymore for this. However we need to keep it for further `electron-forge` builds.

**Comment by CMCDragonkai** [comment]
The nix release build works now.

```
nix-build ./release.nix --attr application
./result/bin/typescript-demo-electron
```

Also I'm pretty sure that the docker build also works if people follow this: https://gist.github.com/CMCDragonkai/f7ca9b3ce8a64aa21ab68cf69dfc9f04

But no one is going to run electron apps in docker right...?

**Comment by CMCDragonkai** [comment]
I'm very close...

Step through debugging of:

```
nix-build ./release.nix --attr deb -K
```

I realised something quite important. This won't work because we actually need the dev dependencies to complete the entire build. But the output of `default.nix` only has the production dependencies. It doesn't have any of the package.json `devDependencies`.

So to deal with this we will need to separate out the utilities inside `default.nix` so that `release.nix` can use those intermediate outputs, the ones that still have the dev dependencies...

**Comment by CMCDragonkai** [comment]
Also alot of dependencies are required by `electron-forge` ahead of time because it was expected to be an interactive tool, not necessarily scripted. So it's asking for `npm` and `git` to be available when it runs even when we won't be loading anything over the network.

**Comment by CMCDragonkai** [comment]
I finally got to the same caching error as @DrFacepalm:

```
building
⠋ Checking your system⠙ Checking your system⠹ Checking your system✔ Checking your system
⠋ Resolving Forge Config✔ Resolving Forge Config
We need to package your application before we can make it
⠋ Preparing to Package Application for arch: x64
An unhandled rejection has occurred inside Forge:
GotError [RequestError]: getaddrinfo ENOTFOUND github.com
    at ClientRequest.<anonymous> (/nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ENOTFOUND',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    href: 'https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  }
}

Electron Forge was terminated. Location:
{}
```

This implies that my caching setup is not working...

**Comment by CMCDragonkai** [comment]
Hmm even though I've set all the right environment variables in `deb` attribute of `release.nix` it is still trying to download from the cache. And it's doing this from when `electron-forge` is executing. Perhaps we cannot use the hash, but have to use the directory name as specified by: https://www.electronjs.org/docs/tutorial/installation#cache

**Comment by CMCDragonkai** [comment]
Need to go back to https://github.com/electron/get/issues/160 and ask around...

**Comment by CMCDragonkai** [comment]
Got some more interesting debug logs with `DEBUG=*`...

```
⠋ Checking your system  electron-forge:check-system checking system, create ~/.skip-forge-system-check to stop doing this +0ms
⠙ Checking your system⠹ Checking your system✔ Checking your system
⠋ Resolving Forge Config  electron-forge:project-resolver searching for project in: /build/typescript-demo-electron +0ms
  electron-forge:project-resolver electron-forge compatible package.json found in /build/typescript-demo-electron/package.json +3ms
✔ Resolving Forge Config
  electron-forge:require-search searching [
  '@electron-forge/maker-deb',
  '/build/typescript-demo-electron/@electron-forge/maker-deb',
  '/build/typescript-demo-electron/node_modules/@electron-forge/maker-deb'
] relative to /build/typescript-demo-electron +0ms
  electron-forge:require-search testing @electron-forge/maker-deb +1ms
  electron-forge:require-search testing /build/typescript-demo-electron/@electron-forge/maker-deb +1ms
  electron-forge:require-search testing /build/typescript-demo-electron/node_modules/@electron-forge/maker-deb +0ms
We need to package your application before we can make it
⠋ Preparing to Package Application for arch: x64  electron-forge:project-resolver searching for project in: /build/typescript-demo-electron +84ms
  electron-forge:project-resolver electron-forge compatible package.json found in /build/typescript-demo-electron/package.json +3ms
  electron-forge:packager packaging with options {
  asar: false,
  overwrite: true,
  dir: '/build/typescript-demo-electron',
  arch: 'x64',
  platform: 'linux',
  afterCopy: [ [AsyncFunction (anonymous)] ],
  afterExtract: [ [AsyncFunction (anonymous)] ],
  afterPrune: [ [AsyncFunction (anonymous)] ],
  out: '/build/typescript-demo-electron/out',
  electronVersion: '12.0.0',
  quiet: true
} +0ms
  electron-packager Electron Packager 15.2.0
  electron-packager Node v14.16.0
  electron-packager Host Operating system: linux 5.4.70 (x64) +0ms
  electron-packager Packager Options: {"asar":false,"overwrite":true,"dir":"/build/typescript-demo-electron","arch":"x64","platform":"linux","afterCopy":[null],"afterExtract":[null],"afterPrune":[null],"out":"/build/typescript-demo-electron/out","electronVersion":"12.0.0","quiet":true} +0ms
  electron-packager Target Platforms: linux +1ms
  electron-packager Target Architectures: x64 +0ms
  get-package-info Getting props:  [ [ 'productName', 'name' ], 'version' ] +0ms
  get-package-info Looking up starting from directory:  /build/typescript-demo-electron +0ms
  get-package-info Result so far: { values: {}, source: {} } +0ms
  get-package-info Checking props in package.json found at: /build/typescript-demo-electron/package.json +4ms
  get-package-info Found prop: [ 'productName', 'name' ] +0ms
  get-package-info Found prop: version +0ms
  get-package-info Found all props! +0ms
  electron-packager Inferring application name from productName in /build/typescript-demo-electron/package.json +0ms
  electron-packager Inferring appVersion from version in /build/typescript-demo-electron/package.json +0ms
  electron-packager Application name: typescript-demo-electron +5ms
  electron-packager Target Electron version: 12.0.0 +0ms
  electron-packager Ignored path regular expressions: [
  '/package-lock\\.json$',
  '/yarn\\.lock$',
  '/\\.git($|/)',
  '/node_modules/\\.bin($|/)',
  '\\.o(bj)?$',
  '/build/electron-packager'
] +0ms
  electron-packager Downloading Electron with options {"platform":"linux","arch":"x64","version":"12.0.0","artifactName":"electron"} +0ms
  @electron/get:index Checking the cache (undefined) for electron-v12.0.0-linux-x64.zip (https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip) +0ms
  @electron/get:index Cache miss +2ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip to /build/electron-download-I9H7r9/electron-v12.0.0-linux-x64.zip with options: undefined +19ms

An unhandled rejection has occurred inside Forge:
GotError [RequestError]: getaddrinfo ENOTFOUND github.com
    at ClientRequest.<anonymous> (/nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/@electron/get/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.EventEmitter.emit (domain.js:467:12)
    at ClientRequest.origin.emit (/nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/@electron/get/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at TLSSocket.EventEmitter.emit (domain.js:467:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  code: 'ENOTFOUND',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    href: 'https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip',
    retry: {
      retries: [Function (anonymous)],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  }
}

Electron Forge was terminated. Location:
{}
```

**Comment by CMCDragonkai** [comment]
Looks like the problem is in:

```
  @electron/get:index Checking the cache (undefined) for electron-v12.0.0-linux-x64.zip (https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip) +0ms
  @electron/get:index Cache miss +2ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v12.0.0/electron-v12.0.0-linux-x64.zip to /build/electron-download-I9H7r9/electron-v12.0.0-linux-x64.zip with options: undefined +19ms
```

It's getting a cache miss here... but why?

**Comment by CMCDragonkai** [comment]
Need to find out why there's a cache miss. Perhaps the `(undefined)` offers a clue here.

Might have to trace the source code a bit to find out what exactly it's looking for...

**Comment by CMCDragonkai** [comment]
The message is output on this line:

https://github.com/electron/get/blob/b42749ac4fc776845a0426db7ee5a8046c62ca1d/src/index.ts#L71

Which implies that `cacheRoot` is undefined. That's not good.

**Comment by CMCDragonkai** [comment]
After looking around in the code. I realised that `@electron/get`  never uses the `electron_config_cache` variable. It just provides a download function expecting the user to pass in the `cacheRoot` option.

The `cacheRoot` option needs to be specified by `electron-packager`. But I don't think it actually uses any environment variable to do this. There's no mention of `electron_config_cache` in the `electron-packager` source code. Instead `electron-packager` exposes a command line program that expects the usage of `--download.cacheRoot=/tmp/cache` as a CLI option.

There's no mention of any environment variable here either?

I'm pretty sure something got lost in translation and this thing was forgotten about. Seems like somewhere we need to specify this for the `electron-packager`, or at least how `electron-forge` calls `electron-packager`.

**Comment by CMCDragonkai** [comment]
The problem is this...

The `electron-packager` exposes a `packager` default export. This is used by `electron-forge` in the `packages/api/core/src/api/package.ts`.

Specifically where it calls `const outputPaths = await packager(packageOpts);`. Through several series of magic, it will eventually call the `downloadArtifact` function in `@electron/get`.

At no point is the `cacheRoot` ever acquired from an environment variable.

The `packageOpts` defined in `packages/api/core/src/api/package.ts` has no mention about download options that would specify the `cacheRoot`.

So currently there is **no** way to set the `cacheRoot` in the latest `electron-forge`.

**Comment by CMCDragonkai** [comment]
EXCEPT....

through the `forge.packagerConfig`.

**Comment by CMCDragonkai** [comment]
There's also https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#electronzipdir as an alternative...

Trying out:

```js
const process = require('process');

module.exports = {
  packagerConfig: {
    // executableName: "typescript-demo-electron",
    download: {
      cacheRoot: process.env.electron_config_cache
    }
  },
  makers: [
    {
      name: '@electron-forge/maker-deb',
    },
  ]
};
```

In the `forge.config.js`.

This does mean that the docs are quite outdated.

**Comment by CMCDragonkai** [comment]
Setting the above solves the caching problem.

**Comment by CMCDragonkai** [comment]
If this works, I would like to try out the other option https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#electronzipdir as described here: https://github.com/electron/electron-packager/commit/9b8bd9c3066b2d120ff92af3fc86b7218e24180a

**Comment by CMCDragonkai** [comment]
It appears the zip dir will be much easier to use, as you don't have to create an entire cache structure, you just need a flat directory containing all the relevant zip files and you don't need the shasum256 either.

However new error:

```
✖ Making for target: deb - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: deb
could not find the Electron app binary at "/build/typescript-demo-electron/out/typescript-demo-electron-linux-x64/@matrixai/typescript-demo-electron". You may need to re-bundle the app using Electron Packager's "executableName" option.
Error: could not find the Electron app binary at "/build/typescript-demo-electron/out/typescript-demo-electron-linux-x64/@matrixai/typescript-demo-electron". You may need to re-bundle the app using Electron Packager's "executableName" option.
    at /build/typescript-demo-electron/node_modules/electron-installer-common/src/installer.js:154:15
    at async Promise.all (index 3)
    at module.exports (/build/typescript-demo-electron/node_modules/electron-installer-debian/src/installer.js:245:3)
    at MakerDeb.make (/build/typescript-demo-electron/node_modules/@electron-forge/maker-deb/src/MakerDeb.ts:39:30)
    at /nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/@electron-forge/core/src/api/make.ts:210:29
```

This might have something to do with the `name` problem @DrFacepalm

**Comment by CMCDragonkai** [comment]
Would be interesting to see if org scoped package names fail...

**Comment by CMCDragonkai** [comment]
It works if I remove the org scoping...

```
  electron-installer-debian Successfully created package at /build/typescript-demo-electron/out/make/deb/x64 +5ms
✔ Making for target: deb - On platform: linux - For arch: x64
```

**Comment by CMCDragonkai** [comment]
Hooray... but org scoping is a problem lol? Even with `executableName`??

**Comment by CMCDragonkai** [comment]
So debian builds are working but rpm builds are not and neither is windows. The windows has a build error involving rcedit.exe. We saw this error before, but I believe this is a different error. I think the reason is that the nix build directory doesn't have a HOME directory.

Here is the error:

```
⠋ Packaging Application  electron-packager Renaming electron.exe to typescript-demo-electron.exe in /build/electron-packager/win32-x64/typescript-demo-electron-win32-x64 +1s
  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"typescript-demo-electron","InternalName":"typescript-demo-electron","OriginalFilename":"typescript-demo-electron.exe","ProductName":"typescript-demo-electron"},"file-version":"1.0.0","product-version":"1.0.0"} +0ms

An unhandled rejection has occurred inside Forge:
Error: rcedit.exe failed with exit code 1. wine: chdir to /homeless-shelter/.wine : No such file or directory
    at ChildProcess.<anonymous> (/nix/store/v9mmqb4afmd4kwv7nkmnfv9v9yzqyp61-node__at_electron-forge_slash_cli-6.0.0-beta.54/lib/node_modules/@electron-forge/cli/node_modules/rcedit/lib/rcedit.js:71:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)

Electron Forge was terminated. Location:
{}
```

The rpm build is failing for other reason as well... will investigate this.

Also the `name` inside `package.json` cannot be org scoped for now. But this is fine, because no Electron apps are distributed on NPM anyway, so it's all a private application at this point similar to TypeScript-Demo-Spa.

**Comment by CMCDragonkai** [comment]
@DrFacepalm Can you try and help debug these builds:

```
nix-build ./release.nix -A package.linux.x64.rpm -K
nix-build ./release.nix -A package.windows.x64.exe -K
```

**Comment by CMCDragonkai** [comment]
I believe we can set the `HOME` environment variable to a temporary directory and allow the wine to fix it up.

Note that I have changed to use `electronZipDir` it works better than using the cache. Since are specifying it in `forge.config.js`, we should also set this up in the `shell.nix`.

Also note that debian package of this simple app is 57 MiB.

**Comment by CMCDragonkai** [comment]
From the IRC:

```
9:08:23 PM - clever: […] mkdir home
9:08:23 PM - clever:     export HOME=$(realpath home)
```

This needs to be tried to create the home directory.

**Comment by CMCDragonkai** [comment]
Home directory issue resolved...

New problem:

```
An unhandled error has occurred inside Forge:
An error occured while making for target: squirrel
Failed with exit code: 1
Output:
Attempting to build package from 'typescript-demo-electron.nuspec'.
Authors is required.

Error: Failed with exit code: 1
Output:
Attempting to build package from 'typescript-demo-electron.nuspec'.
Authors is required.

    at ChildProcess.<anonymous> (/build/typescript-demo-electron/node_modules/electron-winstaller/src/spawn-promise.ts:52:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by CMCDragonkai** [comment]
RPM errors are not due to home directory:

```
✖ Making for target: rpm - On platform: linux - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: rpm
Command failed with a non-zero return code (1):
rpmbuild -bb /build/electron-installer--42-XtQt4VQmku0y/typescript-demo-electron_1.0.0_x86_64/SPECS/typescript-demo-electron.spec --target x86_64 --define _topdir /build/electron-installer--42-XtQt4VQmku0y/typescript-demo-electron_1.0.0_x86_64
Building target platforms: x86_64
Building for target x86_64


RPM build errors:

error: cannot open Packages database in /var/lib/rpm
error: Unable to open temp file: Permission denied
    cannot open Packages database in /var/lib/rpm
    Unable to open temp file: Permission denied
Error: Command failed with a non-zero return code (1):
rpmbuild -bb /build/electron-installer--42-XtQt4VQmku0y/typescript-demo-electron_1.0.0_x86_64/SPECS/typescript-demo-electron.spec --target x86_64 --define _topdir /build/electron-installer--42-XtQt4VQmku0y/typescript-demo-electron_1.0.0_x86_64
Building target platforms: x86_64
Building for target x86_64


RPM build errors:

error: cannot open Packages database in /var/lib/rpm
error: Unable to open temp file: Permission denied
    cannot open Packages database in /var/lib/rpm
    Unable to open temp file: Permission denied
    at ChildProcess.<anonymous> (/build/typescript-demo-electron/node_modules/@malept/cross-spawn-promise/src/index.ts:172:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by CMCDragonkai** [comment]
It appears rpm actually requires a whole VM?

```
9:34:18 PM - clever: CMCDragonkai: run vmTools.runInLinuxVM on the derivation
9:34:40 PM - clever: CMCDragonkai: then it gets ran as root in a vm, and has free access to a fake /, but only the products in $out will persist
```

That will run the whole derivation in a real virtual machine.

**Comment by CMCDragonkai** [comment]
RPM builds work finally by using `vmTools.runInLinuxVM` and `dontFixup = true;` however the result symlink is pointing to a directory rather than to the actual output itself this is strange.

**Comment by CMCDragonkai** [comment]
This is what we get:

```

[nix-shell:~/Projects/Typescript-Demo-Electron]$ tree result2
result2
└── typescript-demo-electron-1.0.0-1.x86_64.rpm

0 directories, 1 file
```

To get it as a single file, we can wrap it with another `runCommand` that makes the file the out.

**Comment by DrFacepalm** [comment]
Windows build giving some odd errors:
```
✔ Packaging Application
Making for the following targets: squirrel
⠋ Making for target: squirrel - On platform: win32 - For arch: x64  electron-windows-installer:main Using Mono: 'mono' +0ms
  electron-windows-installer:main Using Wine: 'wine64' +0ms
  electron-windows-installer:main Created NuSpec file:
  electron-windows-installer:main <?xml version="1.0" encoding="utf-8"?>
  electron-windows-installer:main <package xmlns="http://schemas.microsoft.com/packaging/2010/07/nuspec.xsd">
  electron-windows-installer:main   <metadata>
  electron-windows-installer:main     <id>typescript-demo-electron</id>
  electron-windows-installer:main     <title>typescript-demo-electron</title>
  electron-windows-installer:main     <version>1.0.0</version>
  electron-windows-installer:main     <authors></authors>
  electron-windows-installer:main     <owners></owners>
  electron-windows-installer:main     <iconUrl>https://raw.githubusercontent.com/electron/electron/master/shell/browser/resources/win/electron.ico</iconUrl>
  electron-windows-installer:main     <requireLicenseAcceptance>false</requireLicenseAcceptance>
  electron-windows-installer:main     <description>TypeScript Demo Electron Project</description>
  electron-windows-installer:main     <copyright>Copyright © 2021 </copyright>
  electron-windows-installer:main   </metadata>
  electron-windows-installer:main   <files>
  electron-windows-installer:main     <file src="locales/**" target="lib/net45/locales" />
  electron-windows-installer:main     <file src="resources/**" target="lib/net45/resources" />
  electron-windows-installer:main     <file src="*.bin" target="lib/net45" />
  electron-windows-installer:main     <file src="*.dll" target="lib/net45" />
  electron-windows-installer:main     <file src="*.pak" target="lib/net45" />
  electron-windows-installer:main     <file src="*.exe.config" target="lib/net45" />
  electron-windows-installer:main     <file src="*.exe.sig" target="lib/net45" />
  electron-windows-installer:main     <file src="icudtl.dat" target="lib/net45/icudtl.dat" />
  electron-windows-installer:main     <file src="Squirrel.exe" target="lib/net45/squirrel.exe" />
  electron-windows-installer:main     <file src="LICENSE" target="lib/net45/LICENSE" />
  electron-windows-installer:main     <file src="typescript-demo-electron.exe" target="lib/net45/typescript-demo-electron.exe" />
  electron-windows-installer:main 
  electron-windows-installer:main     <file src="swiftshader/**" target="lib/net45/swiftshader" />
  electron-windows-installer:main 
  electron-windows-installer:main     <file src="vk_swiftshader_icd.json" target="lib/net45" />
  electron-windows-installer:main 
  electron-windows-installer:main   </files>
  electron-windows-installer:main </package>
  electron-windows-installer:main  +7ms
  electron-windows-installer:spawn Spawning mono /build/typescript-demo-electron/node_modules/electron-winstaller/vendor/nuget.exe pack /build/si-202129-42-1i6rbon.dexz/typescript-demo-electron.nuspec -BasePath /build/typescript-demo-electron/out/typescript-demo-electron-win32-x64 -OutputDirectory /build/si-202129-42-1i6rbon.dexz -NoDefaultExcludes +0ms
⠙ Making for target: squirrel - On platform: win32 - For arch: x64⠹ Making for target: squirrel - On platform: win32 - For arch: x64⠸ Making for target: squirrel - On platform: win32 - For arch: x64⠼ Making for target: squirrel - On platform: win32 - For arch: x64⠴ Making for target: squirrel - On platform: win32 - For arch: x64⠦ Making for target: squirrel - On platform: win32 - For arch: x64⠧ Making for target: squirrel - On platform: win32 - For arch: x64⠇ Making for target: squirrel - On platform: win32 - For arch: x64⠏ Making for target: squirrel - On platform: win32 - For arch: x64✖ Making for target: squirrel - On platform: win32 - For arch: x64

An unhandled error has occurred inside Forge:
An error occured while making for target: squirrel
Failed with exit code: 1
Output:
Attempting to build package from 'typescript-demo-electron.nuspec'.
Authors is required.

Error: Failed with exit code: 1
Output:
Attempting to build package from 'typescript-demo-electron.nuspec'.
Authors is required.

    at ChildProcess.<anonymous> (/build/typescript-demo-electron/node_modules/electron-winstaller/src/spawn-promise.ts:52:16)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
```

**Comment by DrFacepalm** [comment]
image

working now, adding the options from: https://js.electronforge.io/maker/squirrel/interfaces/makersquirrelconfig did the trick.

**Comment by DrFacepalm** [comment]
image
Linux zip working

**Comment by DrFacepalm** [comment]
windows zip working

**Comment by CMCDragonkai** [comment]
Merged. The Darwin build still needs to be tested, give the zip to someone with a Mac (not big sur).

Also README.md needs to be fixed up.

Also squash and rebase on master as well to clean up the commit history.

**Comment by DrFacepalm** [comment]
image
darwin build working, ty @Zachaccino

**Pull request merged**
